# Generated by Django 5.1.4 on 2026-02-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type_offre', models.CharField(choices=[('emploi', 'Emploi'), ('stage', 'Stage'), ('freelance', 'Freelance')], default='emploi', max_length=20)),
                ('domaine', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('competences_requises', models.TextField()),
                ('localite', models.CharField(default='Lokossa, Bénin', max_length=100)),
                ('remuneration', models.CharField(blank=True, max_length=100)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='cv/')),
                ('lettre_motivation', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='carrieres.offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-created_at'],
            },
        ),
    ]
