# Generated by Django 5.1.4 on 2026-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrieres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/'),
        ),
    ]
