# Generated by Django 5.1.4 on 2026-02-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_courte', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icone', models.CharField(default='bolt', help_text='Nom icône HeroIcons', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('couleur', models.CharField(default='blue', max_length=30)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('localite', models.CharField(max_length=200)),
                ('description_besoin', models.TextField()),
                ('budget_estime', models.CharField(blank=True, max_length=100)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='services.service')),
            ],
            options={
                'verbose_name': 'Demande de service',
                'verbose_name_plural': 'Demandes de service',
                'ordering': ['-created_at'],
            },
        ),
    ]
