# Generated by Django 5.1.4 on 2026-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePartenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisation', models.CharField(max_length=200)),
                ('type_organisation', models.CharField(max_length=100)),
                ('nom_contact', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('description_projet', models.TextField()),
                ('type_partenariat_souhaite', models.CharField(max_length=200)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_partenaire', models.CharField(choices=[('entreprise', 'Entreprise'), ('institution', 'Institution'), ('ong', 'ONG / Association'), ('autre', 'Autre')], default='entreprise', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/')),
                ('site_web', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
