# Generated by Django 5.1.4 on 2026-02-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_courte', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='projets/')),
                ('client', models.CharField(blank=True, max_length=200)),
                ('localite', models.CharField(blank=True, max_length=200)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, help_text='Ex: Arduino, Raspberry Pi, Zigbee', max_length=300)),
                ('en_vedette', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='projets.categorieprojet')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/gallery/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projets.projet')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
