# Generated by Django 5.1.4 on 2026-02-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='video_principale',
            field=models.FileField(blank=True, help_text='Vidéo de présentation du projet (MP4, WebM…)', null=True, upload_to='projets/videos/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien YouTube / Vimeo à intégrer (alternative à l'upload)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
        migrations.CreateModel(
            name='VideoProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, help_text='Fichier vidéo (MP4, WebM…)', null=True, upload_to='projets/videos/')),
                ('url', models.URLField(blank=True, help_text='Lien YouTube / Vimeo à intégrer')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Vidéo du projet',
                'verbose_name_plural': 'Vidéos du projet',
                'ordering': ['ordre'],
            },
        ),
    ]
