# Generated by Django 5.1.4 on 2026-02-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icone', models.CharField(default='academic-cap', max_length=50)),
                ('couleur', models.CharField(default='blue', max_length=20)),
            ],
            options={
                'verbose_name': 'Catégorie formation',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_courte', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('duree', models.CharField(default='À définir', max_length=100)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_avec_base', models.DecimalField(blank=True, decimal_places=0, help_text='Prix si formé en domotique (ex: MicroPython)', max_digits=10, null=True)),
                ('places_disponibles', models.PositiveIntegerField(default=20)),
                ('actif', models.BooleanField(default=True)),
                ('nouveau', models.BooleanField(default=False)),
                ('en_vedette', models.BooleanField(default=False)),
                ('objectifs', models.TextField(blank=True, help_text='Un objectif par ligne')),
                ('prerequis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.categorieformation')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('niveau_actuel', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('frais_payes', "Frais d'inscription payés"), ('complet', 'Paiement complet'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('fedapay_frais_id', models.CharField(blank=True, max_length=100)),
                ('frais_payes_le', models.DateTimeField(blank=True, null=True)),
                ('fedapay_formation_id', models.CharField(blank=True, max_length=100)),
                ('formation_payee_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
