# Generated by Django 5.1.4 on 2026-05-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_inscription_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFormation',
            fields=[
            ],
            options={
                'verbose_name': 'Paiement formation',
                'verbose_name_plural': 'Paiements formation',
                'ordering': ['-formation_payee_le', '-frais_payes_le', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('formations.inscription',),
        ),
    ]
